Starting catalog tracker org.apache.hadoop.hbase.catalog.CatalogTracker@3568c46
Opening socket connection to server 223.3.80.34/223.3.80.34:2181. Will not attempt to authenticate using SASL (unknown error)
Socket connection established to 223.3.80.34/223.3.80.34:2181, initiating session
Session establishment request sent on 223.3.80.34/223.3.80.34:2181
Session establishment complete on server 223.3.80.34/223.3.80.34:2181, sessionid = 0x35d8cf410090027, negotiated timeout = 40000
catalogtracker-on-hconnection-0x696da30b0x0, quorum=223.3.80.34:2181,223.3.84.42:2181, baseZNode=/hbase Received ZooKeeper Event, type=None, state=SyncConnected, path=null
catalogtracker-on-hconnection-0x696da30b-0x35d8cf410090027 connected
Reading reply sessionid:0x35d8cf410090027, packet:: clientPath:null serverPath:null finished:false header:: 1,3  replyHeader:: 1,193273528489,0  request:: '/hbase/meta-region-server,T  response:: s{180388626460,180388626460,1501250499937,1501250499937,0,0,0,0,61,0,180388626460} 
catalogtracker-on-hconnection-0x696da30b-0x35d8cf410090027, quorum=223.3.80.34:2181,223.3.84.42:2181, baseZNode=/hbase Set watcher on existing znode=/hbase/meta-region-server
Reading reply sessionid:0x35d8cf410090027, packet:: clientPath:null serverPath:null finished:false header:: 2,4  replyHeader:: 2,193273528489,0  request:: '/hbase/meta-region-server,T  response:: #ffffffff0001a726567696f6e7365727665723a3630303230ffffff84ffffffbbffffff964042ffffffd0ffffffedffffffbf50425546a14a77562756e74753310fffffff4ffffffd4318fffffff7ffffff87ffffff82ffffffccffffffd82b100183,s{180388626460,180388626460,1501250499937,1501250499937,0,0,0,0,61,0,180388626460} 
IPC Client (1730704097) connection to ubuntu3/223.3.80.34:60020 from Think: wrote request header call_id: 86 method_name: "Scan" request_param: true
IPC Client (1730704097) connection to ubuntu3/223.3.80.34:60020 from Think: got response header call_id: 86, totalSize: 13 bytes
IPC Client (1730704097) connection to ubuntu3/223.3.80.34:60020 from Think: wrote request header call_id: 87 method_name: "Scan" request_param: true priority: 100
IPC Client (1730704097) connection to ubuntu3/223.3.80.34:60020 from Think: got response header call_id: 87 cell_block_meta { length: 19497 }, totalSize: 19602 bytes
IPC Client (1730704097) connection to ubuntu3/223.3.80.34:60020 from Think: wrote request header call_id: 88 method_name: "Scan" request_param: true priority: 100
IPC Client (1730704097) connection to ubuntu3/223.3.80.34:60020 from Think: got response header call_id: 88, totalSize: 9 bytes
Stopping catalog tracker org.apache.hadoop.hbase.catalog.CatalogTracker@3568c46
Closing session: 0x35d8cf410090027
Closing client for session: 0x35d8cf410090027
Reading reply sessionid:0x35d8cf410090027, packet:: clientPath:null serverPath:null finished:false header:: 3,-11  replyHeader:: 3,193273528490,0  request:: null response:: null
Disconnecting client for session: 0x35d8cf410090027
An exception was thrown while closing send thread for session 0x35d8cf410090027 : Unable to read additional data from server sessionid 0x35d8cf410090027, likely server has closed socket
Session: 0x35d8cf410090027 closed
EventThread shut down
Process identifier=catalogtracker-on-hconnection-0x696da30b connecting to ZooKeeper ensemble=223.3.80.34:2181,223.3.84.42:2181
Initiating client connection, connectString=223.3.80.34:2181,223.3.84.42:2181 sessionTimeout=90000 watcher=org.apache.hadoop.hbase.zookeeper.PendingWatcher@4fa097f4
Starting catalog tracker org.apache.hadoop.hbase.catalog.CatalogTracker@b0994b3
Opening socket connection to server 223.3.80.34/223.3.80.34:2181. Will not attempt to authenticate using SASL (unknown error)
Socket connection established to 223.3.80.34/223.3.80.34:2181, initiating session
Session establishment request sent on 223.3.80.34/223.3.80.34:2181
Session establishment complete on server 223.3.80.34/223.3.80.34:2181, sessionid = 0x35d8cf410090028, negotiated timeout = 40000
catalogtracker-on-hconnection-0x696da30b0x0, quorum=223.3.80.34:2181,223.3.84.42:2181, baseZNode=/hbase Received ZooKeeper Event, type=None, state=SyncConnected, path=null
catalogtracker-on-hconnection-0x696da30b-0x35d8cf410090028 connected
Reading reply sessionid:0x35d8cf410090028, packet:: clientPath:null serverPath:null finished:false header:: 1,3  replyHeader:: 1,193273528491,0  request:: '/hbase/meta-region-server,T  response:: s{180388626460,180388626460,1501250499937,1501250499937,0,0,0,0,61,0,180388626460} 
catalogtracker-on-hconnection-0x696da30b-0x35d8cf410090028, quorum=223.3.80.34:2181,223.3.84.42:2181, baseZNode=/hbase Set watcher on existing znode=/hbase/meta-region-server
Reading reply sessionid:0x35d8cf410090028, packet:: clientPath:null serverPath:null finished:false header:: 2,4  replyHeader:: 2,193273528491,0  request:: '/hbase/meta-region-server,T  response:: #ffffffff0001a726567696f6e7365727665723a3630303230ffffff84ffffffbbffffff964042ffffffd0ffffffedffffffbf50425546a14a77562756e74753310fffffff4ffffffd4318fffffff7ffffff87ffffff82ffffffccffffffd82b100183,s{180388626460,180388626460,1501250499937,1501250499937,0,0,0,0,61,0,180388626460} 
